### PR TITLE
Replaced hardcoded french sourceforge mirrors by generic urls.

### PR DESCRIPTION
**Pull request by fbridault**
Answer to reported issue in main repo https://github.com/fw4spl-org/fw4spl-doc/issues/1
Normally there should be nothing left.

### CODE REVIEW

**Comment by docxu233333333333333333** [comment]
@fbridault  the replacement process failed :(

**Comment by fbridault** [comment]
What do you mean ? Don't pay attention to the appveyor report we were testing it but it can't work correctly yet. Did you try the pull request and do you still have troubles to download some packages ? Could you name them please ?

**Comment by d0cxu** [comment]
@fbridault
So sorry to make you confused.
The list of packages inludes:boost  cppunit  expat freetype  glew  glm icu4c itk png zzip.

**Review by emiliehar — APPROVED** [review]
It works for me on MacOS (10.11.6)

**Comment by fbridault** [comment]
This is weird, all the packages you mention are indeed hosted on sourceforge, except png, I changed it to github in this pull-request. 
Here in France the redirection works fine, in which country do you live ? Do you access to sourceforge main website ? Did you try any of the urls inside the package manually in a web browser, or better with the wget command if you run Linux ? For instance this one : http://downloads.sourceforge.net/project/ogl-math/glm-0.9.6.3/glm-0.9.6.3.zip

Thanks for your feedback

**Comment by greenjava** [comment]
👍 It works for me on Windows 10 (MSVC 2015 update 3)

**Review by greenjava — APPROVED** [review]

**Pull request merged**
